# Generated by Django 4.2.26 on 2025-11-07 08:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Vocabulary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("german_content", models.TextField(verbose_name="德文內容")),
                ("english_content", models.TextField(verbose_name="英文內容")),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("A1", "A1"),
                            ("A2", "A2"),
                            ("B1", "B1"),
                            ("B2", "B2"),
                            ("C1", "C1"),
                            ("C2", "C2"),
                        ],
                        default="A1",
                        max_length=2,
                        verbose_name="語言程度",
                    ),
                ),
            ],
            options={
                "verbose_name": "單字",
                "verbose_name_plural": "單字庫",
            },
        ),
        migrations.CreateModel(
            name="UserError",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(auto_now_add=True, verbose_name="紀錄時間"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="使用者",
                    ),
                ),
                (
                    "vocabulary",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="quiz.vocabulary",
                        verbose_name="錯誤單字",
                    ),
                ),
            ],
            options={
                "verbose_name": "使用者錯誤紀錄",
                "verbose_name_plural": "使用者錯誤紀錄",
                "unique_together": {("user", "vocabulary")},
            },
        ),
    ]
